config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/availabilities', to: 'availabilities#show'
  get '/products/newadmin', to: 'products#newadmin'
  get '/wallets', to: 'products#index'
  resources :posts
  resources :themes
  resources :categories
  resources :currencies
  resources :exchanges
  resources :investors
  resources :incidents
  resources :guides
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", sessions: "sessions" }
  resources :users, :only => [:show, :index, :update] do
      resources :avatars
    end
  resources :products do
      resources :uses
      post 'uses/toggle', to: 'uses#toggle'
      put :like, on: :member
      put :want, on: :member
      collection do # search will apply to more than one product
          get 'search'
      end
      resources :reviews, except: [:show, :index]
    end

  authenticated :user do
    root to: 'exchanges#index', as: :authenticated_root
  end

  root to: 'exchanges#index'
end

app/controllers/uses_controller.rb
class UsesController < ApplicationController
  before_action :authenticate_user!

  def new
    @use = Use.new
  end

  def toggle
    product = Product.friendly.find(params[:product_id])
    if product.uses.where(user: current_user).any?
      @use = Use.where(product: product, user: current_user)
      @use.destroy_all
      render json: { id: current_user.id}
    else
      @use = Use.create(use_params)
      render json: { use: render_to_string('uses/_use-small', layout: false, locals: { use: @use }) }
    end
  end

  private
  def use_params
    params.permit(:product_id, :user_id)
  end
end

app/helpers/uses_helper.rb
module UsesHelper
end

app/views/uses/_button.html.erb
<% @use = product.uses.where(user: user) %>

<% if user_signed_in? %>
  <% if @use.present? %>
    <%= link_to "I'm using this!", product_uses_toggle_path(@product, @use), class: "btn btn-info btn-lg use-button", method: :post, remote: true %>
  <% else %>
    <%= link_to "I use this!", product_uses_toggle_path(product_id: product.id, user_id: user.id), class: "btn btn-info btn-lg use-button", method: :post, remote: true %>
  <% end %>
<% else %>
  <%= link_to "I use this!", pages_login_path, class: "btn btn-info btn-lg use-button-logged-out" %>
<% end %>

app/views/uses/_use-small.html.erb
<div class="small-avatar" id="<%= use.user.id %>"><%= link_to image_tag(use.user.pic), use.user %></div>

app/views/uses/_use.html.erb
<div class="tiny-avatar-list">
  <%= image_tag (use.user.pic) %>
</div>

app/views/uses/_uses.html.erb
<div class="uses">
  <div class="tiny-avatar">
    <% uses.take(3).each do |use| %>
      <%= image_tag(use.user.pic) %>
    <% end %>
  </div>
</div>