config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/availabilities', to: 'availabilities#show'
  get '/products/newadmin', to: 'products#newadmin'
  get '/wallets', to: 'products#index'
  resources :posts
  resources :themes
  resources :categories
  resources :currencies
  resources :exchanges
  resources :investors
  resources :incidents
  resources :guides
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", sessions: "sessions" }
  resources :users, :only => [:show, :index, :update] do
      resources :avatars
    end
  resources :products do
      resources :uses
      post 'uses/toggle', to: 'uses#toggle'
      put :like, on: :member
      put :want, on: :member
      collection do # search will apply to more than one product
          get 'search'
      end
      resources :reviews, except: [:show, :index]
    end

  authenticated :user do
    root to: 'exchanges#index', as: :authenticated_root
  end

  root to: 'exchanges#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :theme
	has_many :products

	extend FriendlyId
	friendly_id :name, use: :slugged

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :set_themes, only: [:new, :show, :index, :edit, :create, :update]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @themes = Theme.all.includes(:categories => :products).order(created_at: :asc)
    @categories = Category.all.includes(:products).order(name: :asc)
  end

  def show
    @products = @category.products.includes([:reviews], [:uses => [:user => :avatar]]).order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_category
    @category = Category.friendly.find(params[:id])
  end

  def set_themes
    @themes = Theme.all
  end

  def category_params
    params.require(:category).permit(:name, :description, :theme_id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category_row.html.erb
<div class="col-xs-6 col-sm-3 col-md-3 category-row page">
  <div class="category-image">
    <%= link_to image_tag(category.products[-1].try(:image).try(:med_thumb)), category %>
  </div>
  <div clas="category-name">
    <%= link_to category.name.titleize.pluralize, category %>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
<% if @category.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

  <ul>
    <% @category.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.label :name %><br>
  <%= f.text_area :name, class: "form-control", rows: "1" %>
</div>
<div class="form-group">
  <%= f.label :description %><br>
  <%= f.text_area :description, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label "Theme" %><br>
  <%= f.select :theme_id, @themes.collect {|theme| [theme.name.titleize, theme.id]}, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.submit class: "btn btn-primary btn-0lg" %>
</div>
<% end %>

app/views/categories/_header.html.erb
<div class="index-panel">
  <h1><%= category.name.pluralize.titleize %></h1>
  <h4><%= (category.description).gsub(/\n/, '<br/>').html_safe %></h4>
  <br>
  <% if user_signed_in? %>
  <div class= "new-product-panel">
    <div class= "form-group">
      <%= link_to 'Add a new ' + category.name.titleize, new_product_path, class: "btn btn-primary btn-lg" %>
    </div>
  </div>
  <% end %>
</div>
  <div class="title">
    <%= pluralize(@products.count, "Product") %>
  </div>

app/views/categories/_header_index.html.erb
<div class="index-panel">
  <h1>Find products</h1>
  <h4>Get clicking for cleansing, moisturizing, treating...and everything in between!</h4>
</div>
<div class= "new-product-panel">
  <div class= "form-group">
    <%= link_to 'Add product!', new_product_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

app/views/categories/_header_show.html.erb
<div class="category-show-header">
  <h1><%= category.name.pluralize.titleize %></h1>
  <!-- <%= (category.description).gsub(/\n/, '<br/>').html_safe %> -->
  <!-- <% if user_signed_in? %>
    <div class= "add-button">
      <div class= "form-group">
        <%= link_to 'Add a ' + category.name.titleize, new_product_path, class: "btn btn-primary btn-lg" %>
      </div>
    </div>
  <% end %> -->
</div>

<div class="title">
  <%= pluralize(@products.count, "Product") %>
</div>

<%= render 'products/sort' %>

app/views/categories/_meta.html.erb
<% title category.name.pluralize.titleize + '' %>
<% description '' + category.name.pluralize %>
<% keywords category.name.pluralize + '' %>

app/views/categories/edit.html.erb
<% nofollow %>
<% noindex %>
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% title '' %>
<% description '' %>
<% keywords '' %>


<div class="category-index">
  <%= render partial: 'themes/theme_row', collection: @themes, as: :theme %>
</div>

app/views/categories/new.html.erb
<% nofollow %>
<% noindex %>
<h1>New Category</h1>
<%= render 'form' %>
<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<% title @category.name %>
<% description '' %>
<% keywords '' %>


<%= render partial: 'meta', locals: { category: @category } %>
<!-- <%= render 'products/search' %> -->
<div class="page">
<%= render partial: 'header_show', locals: { category: @category } %>


<div class="sortable">
  <%= render partial: 'products/product_row', collection: @products, as: :product %>
</div>
</div>

<!-- <script>
  mixpanel.track("Viewed Category", {"Category Name": "<%= @category.name %>", "Category ID": <%= @category.id %>});
</script> -->

<script>
  $('.star-rating').raty({
    path: 'https://s3.amazonaws.com/productbase/stars',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>