config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/availabilities', to: 'availabilities#show'
  get '/products/newadmin', to: 'products#newadmin'
  get '/wallets', to: 'products#index'
  resources :posts
  resources :themes
  resources :categories
  resources :currencies
  resources :exchanges
  resources :investors
  resources :incidents
  resources :guides
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", sessions: "sessions" }
  resources :users, :only => [:show, :index, :update] do
      resources :avatars
    end
  resources :products do
      resources :uses
      post 'uses/toggle', to: 'uses#toggle'
      put :like, on: :member
      put :want, on: :member
      collection do # search will apply to more than one product
          get 'search'
      end
      resources :reviews, except: [:show, :index]
    end

  authenticated :user do
    root to: 'exchanges#index', as: :authenticated_root
  end

  root to: 'exchanges#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :reviews, dependent: :destroy
	has_many :photos, dependent: :destroy
	has_many :likes
	has_many :users, through: :likes
	has_many :liked_by, through: :likes, source: :user #rename user_id to liked_by in likes table for referencing from products
	belongs_to :category
	has_many :links
	has_many :uses, dependent: :destroy
	has_many :used_by, through: :uses, source: :user #rename user_id to used_by for referencing
	has_many :wants, dependent: :destroy
	has_many :wanted_by, through: :wants, source: :user
	has_many :product_posts
	has_many :posts, through: :product_posts
	has_many :currency_products
	has_many :currencies, through: :currency_products
	validates :name, :category, presence: true

	extend FriendlyId
	friendly_id :slug_candidates, use: :slugged

	def slug_candidates
		[
			[:name]
		]
	end

	def should_generate_new_friendly_id?
		name_changed?
	end

	mount_uploader :image, ImageUploader

	searchkick

	def self.popular
		Product.find(Product.joins(:uses).group('products.id').order("count(*) desc").limit(10).ids).shuffle
	end

	def self.most_wanted
		Product.find(Product.joins(:wants).group('products.id').order("count(*) desc").limit(3).ids)
	end

	def self.most_reviewed
		Product.find(Product.joins(:reviews).group('products.id').order("count(*) desc").ids)
	end

	def self.best
		best = []
		Product.all.each do |product|
			if product.average_rating == 5
				best << product
			end
		end
		best.take(3).shuffle
	end

	def recent_reviews
		reviews.includes(:user => :avatar).order(created_at: :desc)
	end

	def recent_uses
		uses.order(created_at: :desc)
	end

	def recent_wants
		wants.order(created_at: :desc)
	end

	def average_rating
		if self.rating.present? && !self.reviews.any?
			joint_rating = self.rating
		elsif !self.rating.present? && self.reviews.any?
			joint_rating = reviews.average(:rating).round(1)
		elsif self.rating.present? && self.reviews.any?
			joint_rating = ((self.rating + reviews.average(:rating))/2).round(1)
		elsif self.rating.blank?
			joint_rating = 0
		end
		joint_rating
	end

	def swatches
		posts.where("url like ?", "%" + "instagram" + "%")
	end

	def tutorials
		posts.where("url like ?", "%" + "youtube" + "%")
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :like, :use, :want, :destroy]
  before_action :authenticate_user!, except: [:search, :show, :index, :new, :create]
  before_action :check_user, except: [:search, :index, :show, :create, :new, :like, :use, :want, :update]
  before_action :set_categories, only: [:new, :edit, :create, :update]
  before_action :set_themes, only: [:new, :edit, :create, :update]

  def search
      @query = params[:search]
      # @products = Product.search(params[:search], include: [ { uses: { user: :avatar } }, :reviews])
      @products = Product.search(params[:search])
      @exchanges = Exchange.search(params[:search])
      # @categories = Category.search(params[:search], include: [:products])
      # @categories = Category.search(params[:search])
      # @default = Category.all.includes(:products)
  end

  def index
    @products = Product.all.order(popular: :desc)
  end

  def show
    @review = Review.new
  end

  def new
    @product = Product.new
    @product.category_id = 1 #default to category 1 for now
  end

  def newadmin
    @product = Product.new
    @categories = Category.all
  end

  def like
    type = params[:type]
    if type == 'like'
      current_user.liked_products << @product
      redirect_to :back
    elsif type == 'unlike'
      current_user.liked_products.delete(@product)
      redirect_to :back
    else
      redirect_to :back
    end
  end

  def use
    type = params[:type]
    if type == 'use'
      current_user.used_products << @product
      redirect_to :back

      # $tracker.track(current_user.id, 'Added Use', {
      #   'Product ID' => @product.id,
      #   'Product Name' => @product.name
      #   })
      elsif type == 'unuse'
        current_user.used_products.delete(@product)
        redirect_to :back
      else
        redirect_to :back
      end
    end

    def want
      type = params[:type]
      if type == 'want'
        current_user.wanted_products << @product
        redirect_to :back

        # $tracker.track(current_user.id, 'Added Want', {
        #   'Product ID' => @product.id,
        #   'Product Name' => @product.name
        #   })
        elsif type == 'unwant'
          current_user.wanted_products.delete(@product)
          redirect_to :back
        else
          redirect_to :back, notice: 'Nothing happened.'
        end
      end

      def edit
      end

      def create
        @product = Product.new(product_params)
        @product.remote_image_url = product_params[:image]
        @product.user_id = current_user.id
        @product.category_id = 1
        @product.theme_id = @product.category.theme_id
        respond_to do |format|
          if @product.save
            format.html { redirect_to @product, notice: 'Product was successfully created.' }
            format.json { render :show, status: :created, location: @product }

            # $tracker.track(current_user.id, 'Added Product', {
            #   'Product ID' => @product.id,
            #   'Product Name' => @product.name
            #   })
            else
              format.html { render :new }
              format.json { render json: @product.errors, status: :unprocessable_entity }
            end
          end
        end

        def update
          respond_to do |format|
            if @product.update(product_params)
              format.html { redirect_to @product, notice: 'Product was successfully updated.' }
              format.json { render :show, status: :ok, location: @product }
            else
              format.html { render :edit }
              format.json { render json: @product.errors, status: :unprocessable_entity }
            end
          end
        end

        def destroy
          @product.destroy
          respond_to do |format|
            format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
            format.json { head :no_content }
          end
        end

        private
        def set_product
          @product = Product.friendly.find(params[:id])
        end

        def check_user
          unless current_user.admin?
            redirect_to root_url, alert: "Sorry, only admins can do that!"
          end
        end

        def set_themes
          @themes = Theme.all
        end

        def set_categories
          @categories = Category.all.order(name: :asc)
        end

        def product_params
          params.require(:product).permit(:name, :device, :image, :category_id, :user_id, :about, :theme_id, :link, :rating, :location, :url, :founded_date, :access_private_keys, :popular, :popular_more, :price)
        end

      end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_admin.html.erb
<% if user_signed_in? && current_user.admin %>
<div class="row">
	<p>Product Id: <%= product.id %></p>
	<%= link_to 'Edit', edit_product_path(product), class: "btn btn-link" %> |
	<%= link_to 'Product', products_path, class: "btn btn-link" %> |
	<%= link_to 'New', new_product_path, class: "btn btn-link" %> |
	<%= link_to "Destroy", product, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
<% end %>

app/views/products/_form.html.erb
<%= form_for(@product, :html => { multipart: true }) do |f| %>
  <% if @product.errors.any? %>
  <div id="error_explanation" class= "alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <h4><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h4>

    <ul>
      <% @product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_area :name, placeholder: "Name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_area :url, placeholder: "URL", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :device %>
    <%= f.text_field :device, placeholder: "Web, Desktop, Mobile, Offline", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, placeholder: "Location", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :launch_year %>
    <%= f.text_field :founded_date, placeholder: "Launch year", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :slug %>
    <%= f.text_field :slug, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :about %>
    <%= f.text_area :about, class: "form-control", rows:5  %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :platform %>
    <%= f.text_field :platform, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :access_private_keys %>
    <%= f.check_box :access_private_keys, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :popular %>
    <%= f.check_box :popular, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label "More info about wallet popularity" %>
    <%= f.text_area :popular_more, class: "form-control", rows:5  %>
  </div>
  <div class="form-group">
    <%= f.submit value: "Submit", class: "btn btn-primary btn-lg" %>
  </div>

<% end %>

app/views/products/_login.html.erb
<% if devise_mapping.omniauthable? && !user_signed_in? %>
<% resource_class.omniauth_providers.each do |provider| %>
<%= link_to "Continue with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider), class: "btn btn-lg fb-button" %><br />
<% end %>
<% end %>

app/views/products/_metadata.html.erb
<!-- in <%= link_to product.category.name.pluralize.titleize, product.category %> -->
<%= render partial: "rating", locals: { product: @product } %>

app/views/products/_product_row.html.erb
<tr>
  <td>
    <%= link_to image_tag(product.image.small_thumb), product %>
  </td>
  <td>
    <%= link_to product.name, product, class: "product-info" %>
  </td>
  <td>
    <% if product.device.present? %>
    	<% if product.device.downcase.include?("web") %><h5><i class="fa fa-globe" aria-hidden="true"></i> &nbsp;Web</h5><% end %>
    	<% if product.device.downcase.include?("mobile") %><h5><i class="fa fa-mobile" aria-hidden="true"></i> &nbsp;Mobile</h5><% end %>
    	<% if product.device.downcase.include?("desktop") %><h5><i class="fa fa-desktop" aria-hidden="true"></i> &nbsp;Desktop</h5><% end %>
    	<% if product.device.downcase.include?("offline") %><h5><i class="fa fa-suitcase" aria-hidden="true"></i> &nbsp;Hardware</h5><% end %>
    <% end %>
  </td>
  <td>
    <% if product.access_private_keys? %><i class="fa fa-check" aria-hidden="true"></i><% end %>
  </td>
  <td>
    <% if product.popular? %><i class="fa fa-check" aria-hidden="true"></i><% end %>
  </td>
</tr>

app/views/products/_product_row_review.html.erb
<div class="row product-row">
  <div class="col-xs-3 product-image">
    <%= link_to image_tag(product.image.url), product %>
  </div>

  <div class="col-xs-8">
    <div class="product-brand"><%= product.product_brand %></div>
    <div class="product-name"><%= link_to product.product_name, product %></div>
    <br/>
    <% if product.reviews.where(user: @user).any? %>
      <%= product.reviews.where(user: @user).first.comment %>
    <% end %>
  </div>

  <div class="col-xs-1 review-info">
    <%= render partial: 'products/rating', locals: {rating: product.average_rating} %>
  </div>
</div>

app/views/products/_product_row_user.html.erb
<div class="row product-row">
  <div class="col-xs-4 col-sm-3 product-image">
    <%= link_to image_tag(product.image.small_thumb), product %>
  </div>

  <div class="col-xs-5 col-sm-6">
    <div class="product-name"><%= link_to product.name, product %></div>
    <br/>
    <% if product.reviews.where(user: @user).any? %>
      <%= truncate(product.reviews.where(user: @user).first.comment, length: 70) %>
    <% end %>
  </div>

  <div class="col-xs-3 col-sm-3 review-info">
    <% if product.reviews.where(user: @user).any? %>
      <%= render partial: 'products/rating_single', locals: {rating: product.reviews.where(user: @user).first.rating} %>
    <% end %>
  </div>
</div>

app/views/products/_rating.html.erb
<% unless @product.average_rating == 0 %>
  <div class="rating">
    <%= product.average_rating %>
  </div>
<% end %>

app/views/products/_rating_single.html.erb
<div class="rating-single">
  <%= rating.round(0) %>
</div>

app/views/products/_sort.html.erb
<div class="sorts">
  <i class="fa fa-sort" aria-hidden="true"></i>
  <%= link_to "Name", root_path, id: "name" %>
  <%= link_to "Users", root_path, id: "users" %>
  <%= link_to "Rating", root_path, id: "rating" %>
</div>

app/views/products/edit.html.erb
<% nofollow %>
<% noindex %>
<h1>Edit  product #<%= @product.id %></h1>

<%= render 'form' %>


<%= link_to 'Show', @product, class: "btn btn-link" %> |
<%= link_to 'Back', products_path, class: "btn btn-link" %>

app/views/products/index.html.erb
<% title 'Walletthing' %>
<% description 'The easiest place to compare cryptocurrency wallets' %>
<% keywords 'cryptocurrency wallets, bitcoin, ethereum, how to buy bitcoin, how to buy ethereum, how to buy ether, how to buy litecoin, how to store cryptocurrency, digital money' %>

<div class="jumbotron">
  <h2>Buy your first Bitcoin in New York</h2>
  <h4>Simple and reliable information for buying and storing Bitcoin in NYC.</h4>
  <div class="btn-group" role="group" aria-label="...">
    <%= link_to "1. Buy at an Exchange", exchanges_path, class: "btn btn-default selector" %>
    <%= link_to "2. Store in a Wallet", wallets_path, class: "btn btn-default selector selected" %>
  </div>
</div>atom
</p>
<div class="table-responsive">
              <table class="table">
                <thead>
                    <th>Wallet</th>
                    <th>Name</th>
                    <th>Device</th>
                    <th>Private Keys?</th>
                    <th>Popular?</th>
                </thead>
                <% @products.each do |product| %>
                  <%= render partial: 'product_row', locals: { product: product } %>
                <% end %>
              </table>
            </div>

<script>
mixpanel.track("Viewed Home");
<% if current_user %>
mixpanel.identify("<%= current_user.id %>");
mixpanel.people.set({
  "$email" : "<%= current_user.email %>",
  "name" : "<%= current_user.user_name %>",
  "User ID" : "<%= current_user.id %>",
  <% end %>
});
</script>

<script>
mixpanel.track_links(".feed-user a", "Clicked Feed", {"Item" : "User"})
mixpanel.track_links(".review-item a", "Clicked Feed", {"Item" : "Review"});
mixpanel.track_links(".use-item a", "Clicked Feed", {"Item" : "Use"});
mixpanel.track_links(".want-item a", "Clicked Feed", {"Item" : "Want"});
mixpanel.track_links(".post-item a", "Clicked Feed", {"Item" : "Post"});
</script>

app/views/products/search.html.erb
<div class="page">
<% if @products.empty? && @exchanges.empty? %>
<div class="page-header">
  <h1>Hm, no matches for <strong><%= @query %></strong> yet.</h1>
</div>
<% end %>


<% if @products.any? %>
  <div class="sortable">
    <ul class="list-group">
      <% @products.each do |product| %>
      <li class="list-group-item">
      <%= render partial: 'product_row', locals: { product: product } %>
    </li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @exchanges.any? %>
  <div class="sortable">
    <ul class="list-group">
      <% @exchanges.each do |exchange| %>
      <li class="list-group-item">
      <%= render partial: 'exchanges/exchange_row', locals: { exchange: exchange } %>
    </li>
      <% end %>
    </ul>
  </div>
<% end %>



</div>

<script>
  mixpanel.track("Viewed Search Results", {"Search Term": "<%= @query %>"});
</script>

app/views/products/show.html.erb
<% title @product.name + ' on Walletthing' %>
<% description 'Reviews, currencies, and how to get started with ' + @product.name %>
<% keywords 'cryptocurrency wallets, bitcoin, ethereum, how to buy bitcoin, how to buy ethereum, how to buy ether, how to buy litecoin, how to store cryptocurrency, digital money' %>

<i class="fa fa-long-arrow-left" aria-hidden="true"></i>&nbsp;<%= link_to "Back to Wallets", wallets_path %>
<hr>

<div class="col-xs-12 col-sm-5">
	<h1><%= @product.name %></h1> <%= render partial: "metadata", locals: { product: @product } %>
	<% if @product.image? %>
		<div class = "product-image">
			<%= image_tag @product.try(:image).try(:med_thumb) %>
		</div>
		</br>
	<% end %>


	<div class="related">
		<%= render partial: 'product_row', collection: @product.category.products.sample(0), as: :product %>
	</div>
</div>

<div class="col-xs-12 col-sm-7">


		<% if @product.location.present? || @product.founded_date.present? %>
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title">Company</h3>
		  </div>
		  <div class="panel-body">
		    <h5>
		      <% if @product.location? %>
		        <i class="fa fa-map-marker" aria-hidden="true"></i> &nbsp;
		        <%= @product.location %>
		      <% end %>
		    </p>
		    <% if @product.founded_date? %>
		      <i class="fa fa-calendar" aria-hidden="true"></i> &nbsp;
		      <%= @product.founded_date %>
		      <% end %>
		    </h5>
		  </div>
		</div>
		<% end %>

		<% if @product.device? || @product.platform? || @product.access_private_keys? %>
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title">Specs</h3>
		  </div>
		  <div class="panel-body">
		    <h5>
					<% if @product.url? %>
						<i class="fa fa-map-marker" aria-hidden="true"></i> &nbsp;
						<%= link_to "Official Website", @product.url %>
					<% end %>
				</p>
					<% if @product.price? %>
						<i class="fa fa-usd" aria-hidden="true"></i> &nbsp;
						<%= @product.price %>
					<% end %>
				</p>
		      <% if @product.device? %>
						<% if @product.device.downcase.include?("web") %><h5><i class="fa fa-globe" aria-hidden="true"></i> &nbsp;Web wallet</h5><% end %>
						<% if @product.device.downcase.include?("mobile") %><h5><i class="fa fa-mobile" aria-hidden="true"></i> &nbsp;Mobile wallet</h5><% end %>
						<% if @product.device.downcase.include?("desktop") %><h5><i class="fa fa-desktop" aria-hidden="true"></i> &nbsp;Desktop wallet</h5><% end %>
						<% if @product.device.downcase.include?("offline") %><h5><i class="fa fa-suitcase" aria-hidden="true"></i> &nbsp;Hardware wallet</h5><% end %>
		      <% end %>
		    </p>
		    <% if @product.platform? %>
		      <h5><i class="fa fa-calendar" aria-hidden="true"></i> &nbsp;</h5>
		      <%= @product.platform %>
		    <% end %>
				<% if @product.access_private_keys? %>
					<h5><i class="fa fa-key" aria-hidden="true"></i> &nbsp;Private Keys Available</h5>
				<% end %>
		    </h5>
		  </div>
		</div>
		<% end %>

	<!-- <% if @product.currencies.any? %>
		<h5><i class="fa fa-money" aria-hidden="true"></i> &nbsp;
		<% @product.currencies.each do |currency| %>
			<%= link_to currency.name, currency %>&nbsp;
		<% end %>
	<% end %>
	</h5>
		<%= @product.about %>
	</p>
	</br> -->

	<% if @product.popular? || @product.popular_more %>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Discussion</h3>
		</div>
		<div class="panel-body">
			<h5>
				<% if @product.popular? %>
					<i class="fa fa-bolt" aria-hidden="true"></i> &nbsp;
					<%= @product.name %> is popular among experts on BitcoinTalk and Reddit
				<% end %>
			</p>
			<% if @product.popular_more? %>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= sanitize @product.popular_more, tags: %w(strong br p a href), attributes: %w(href) %>
				<% end %>
			</h5>
		</div>
	</div>
	<% end %>

<% if !user_signed_in? %>
	<div class="panel panel-default panel-default-main">
	  <div class="panel-body panel-body-main"><h3>Share your experience with <%= @product.name %></h3></div>
		<%= render partial: "login" %>
	</div>
<% end %>


	<% unless @product.reviews.where(user: current_user).any? %>
		<%= render partial: "reviews/form" %>
	<% end %>

	<div class="reviews">
		<%= render partial: "reviews/row", collection: @product.recent_reviews, as: :review %>
	</div>
</div>
</div>


<%= render partial: "devise/sessions/form_layer" %>

	<script>
	$('.star-rating').raty({
		path: 'https://s3.amazonaws.com/productbase/stars',
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});
	</script>

	<script>
	mixpanel.track("Viewed Product", {"Product Name": "<%= @product.name %>", "Product ID": <%= @product.id %>});
	</script>